language: swift

osx_image: 
- xcode10.2

env:
- SCHEME=Cacher SWIFT_VERSION=5.0

cache: bundler

before_install:
  - gem update --system
  - gem install bundler

xcode_project: Cacher.xcodeproj

xcode_scheme: Cacher

script:
  - bundle exec fastlane test_ci