language: swift

osx_image: 
- xcode10.1
- xcode10.2

env:
- SCHEME=Cacher SWIFT_VERSION=5.0
- SCHEME=Cacher SWIFT_VERSION=4.2
- SCHEME=Cacher SWIFT_VERSION=4.0

cache: bundler

before_install:
  - gem update --system
  - gem install bundler

matrix:
  exclude:
  - osx_image: xcode10.1
    env: SCHEME=Cacher SWIFT_VERSION=5.0
  
script:
  - bundle exec fastlane test_ci
