# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

def shared_pods
 pod 'SwiftyJSON', '~> 5.0.0'
end

target 'CacherExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CacherExample
	shared_pods
end
