# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

def shared_pods
 pod 'Alamofire', '~> 4.8.2'
 pod 'ReachabilitySwift', '~> 4.3.1'
 pod 'SwiftyJSON', '~> 5.0.0'
end

target 'CacherExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CacherExample
	shared_pods
end
